apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-metrics-endpoint
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-endpoint
subjects:
- kind: User
  name: admin@example.com
- kind: ServiceAccount
  name: default
  namespace: default
